### ISSUE TITLE
生成黄金ftx报价

### ISSUE THREAD

**Issue by xinCoder2019** [FAN-finance/stock#12]
1、gold杠杆报价改为3倍（之前是10倍）：gold3l，gold3s
2、报价生成开始时间：北京时间：2021年8月23日 14:00:00，初始rebalance价格：5300
3、 twelvedata报价时间：每周日UTC 22点开始，每周五UTC 21点休市

**Comment by wxf4150** [comment]
![2021-08-23 09-06-22 的屏幕截图](https://user-images.githubusercontent.com/5011771/130376949-817c3746-ee3f-4be3-a6b1-9d5cf526f339.png)

---------------------------------------
image2:
![2021-08-23 09-06-04 的屏幕截图](https://user-images.githubusercontent.com/5011771/130376953-1f45c3d3-f1b8-43b9-92d1-4d7023ad472f.png)

每周五UTC 13点休市

**Comment by wxf4150** [comment]
按分钟的：
![2021-08-23 09-17-53 的屏幕截图](https://user-images.githubusercontent.com/5011771/130377438-0f062680-0f38-40e6-8237-e40fafc1a8f5.png)
按小时的到显示13点。  按分钟的是显示21点。  
我们的用21点吧。

**Comment by wxf4150** [comment]
已经处理
