### ISSUE TITLE
关于资产开盘时间字段的说明

### ISSUE THREAD

**Issue by obdCoder** [FAN-finance/stock#2]
当前获取资产的价格是一个小时之内的最大值和最小值，在开盘的最初一个小时之内，因为不满一个小时的要求，这个时间段对于当前这个应用来说，不能算是开市。
而又由于预言机是独立的提供服务，不应该为某个特定的应用提供特定的服务，这种具体的应用开市时间就放到前端来判断，所以需要预言机提供资产的开盘时间。

**Comment by wxf4150** [comment]
>>>预言机是独立的提供服务，不应该为某个特定的应用提供特定的服务

"价格服务接口" 和"开市状态"这是两种不同的数据,不同的接口.
你一直想把 "价格服务接口" 响应数据,捆绑"开市时间,开市状态",
  我觉得这个,你主要是想用来方便目前写的这个"特定的"前端项目. 主要是用来方便你的这段前端的js代码,少调用1个请求 .

**Comment by obdCoder** [comment]
每一个资产都会对应不同的开盘时间，和价格信息一起返回给前端，逻辑上也是很通畅的

**Comment by wxf4150** [comment]
确实方便了你这段前端的js代码,少调用1个请求 . 

你要知道几乎所有交易所的股票价格接口都没你这逻辑,绑定上开盘时间和状态,  用来方便自家的交易所app调用或是方便你写这段js.

**Comment by obdCoder** [comment]
嗯，是方便了，能提供方便，那就请加上吧

**Comment by wxf4150** [comment]
没有必要. 无需要添加. 直接使用"开市状态"接口
