### ISSUE TITLE
ftx调仓触发时机

### ISSUE THREAD

**Issue by xinCoder2019** [FAN-finance/stock#7]
ftx的仓位触发时机有：
1、当日内价格波动超过10%的时候，触发调仓，波动超过10%，就以10%作为调仓比例，比如：上一次的价格是10,在某一个检测周期，涨了20%，那么价格应该处理为10乘以1.1等于11；如果是下跌了20%，即变为10乘以0.9等于9
2、当天没有触发调仓，需要每天14点触发一次调仓

bullPrice计算公式 p2_btc3x＝p1_btc3x*(((p2_btc-p1_btc)/p1_btc)*3)+1)

**Comment by neocarmack** [comment]
上面是不是打错了？：
1. 
比如：上一次的价格是10,在某一个检测周期，涨了10%，那么价格应该处理为10乘以1.1等于11；如果是下跌了10%，即变为10乘以0.9等于9

2. 当天如果波动幅度没有达到10%触发调仓，那么每天凌晨两点触发一次调仓，比如：当天波动5%，从10块到10.5块，那么第二天的起始价格就是10.5, 第二天的日内波动，以10.5作为bullPrice公式里的p1_btc的参数值

**Comment by neocarmack** [comment]
上面是不是打错了？：
1. 
比如：上一次的价格是10,在某一个检测周期，涨了10%，那么价格应该处理为10乘以1.1等于11；如果是下跌了10%，即变为10乘以0.9等于9

2. 当天如果波动幅度没有达到10%触发调仓，那么每天凌晨两点触发一次调仓，比如：当天波动5%，从10块到10.5块，那么第二天的起始价格就是10.5, 第二天的日内波动，以10.5作为bullPrice公式里的p1_btc的参数值

**Comment by xinCoder2019** [comment]
第一种情况是针对：在极端的情况下，10秒中内，如果价格波动超过了10%，假如实际是20%，那么调整的幅度也始终按照10%调整，而不是以实际的20%调整

**Comment by neocarmack** [comment]
也就是说，超过10%的部分，统一按照10%来计算，是吧，这个是可以的。

**Comment by xinCoder2019** [comment]
嗯，是这个意思

**Comment by wxf4150** [comment]
> 在每日协调世界时(UTC)为00:02:00时，杠杆代币将在FTX上进行”调仓“来让杠杆代币的杠杆率回归目标水平。

我们是在需要每天14点触发一次调仓吗？

已经完成了哈

**Comment by wxf4150** [comment]
知道了，我们不用使用ftx的utc 00:02:00,   我们要14点调。

**Comment by wxf4150** [comment]
已经重构过多次了
