### ISSUE TITLE
需要修改的四点内容

### ISSUE THREAD

**Issue by xinCoder2019** [FAN-finance/stock#8]
1、Signs数组的Sign字段不要输出给前端
2、实现controls/dex.go里面的TODO 验证数据签名（当前版本的539行）
3、修正千分之一的价格保护：是平均值与每个节点的报价进行比较，当前逻辑只是和当前节点的价格进行了比较
4、utils/log_rotation.go的syscall.SIGUSR1在window环境下找不到

**Comment by wxf4150** [comment]
当前平均值与每个节点的报价进行千分之一比较，有一个超出千分之一,就不签名？

**Comment by wxf4150** [comment]
已处理
